### ISSUE TITLE
support:  how should we set the values in contract/neardev

### ISSUE THREAD

**Issue by charleslavon** [milenakrawczyk/loyalty-program-with-ft#7]
# Support Question
I've tried a couple ways, but have not been able to successfully create the FT after deploying the contract to a subaccount of my testnet address.  It looks like we need to use nearcli to manually create the subaccount and then set the sub account address as an environment variable. @milenakrawczyk  Is that correct?

I've tried the following
`neardev/dev-account contains 00711.testnet`
`neardev/dev-account.env contains CONTRACT_NAME=program.00711.testnet`

`neardev/dev-account contains program.00711.testnet`
`neardev/dev-account.env contains CONTRACT_NAME=program.00711.testnet`

**Comment by charleslavon** [comment]
Alternatively, if we try to use the automatically created dev-contract-address, where do we find the keys to that address such that we can log into wallet and sign transactions?

**Comment by milenakrawczyk** [comment]
The README file has been updated to reflect all the steps needed to run the project locally:
https://github.com/milenakrawczyk/loyalty-program-with-ft/pull/8
